title: ruvieye's blog
email: ruvieye@naver.com
description: Continuous devlog
author: ruvieye
baseurl: ""
url: "http://ruvieye.github.io"

# Social Profiles
twitter_username:  ruvieye
github_username:   ruvieye
facebook_username: ruvieye

# Build settings
markdown:          kramdown
paginate:          7
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist