#jekyll theme clean blog site
#https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll

title: 이제고고
email: ruvieye@naver.com
description: >- # this means to ignore newlines until "baseurl:"
 개발자가 되려면
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: ruvieye
github_username:  ruvieye

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
